# Generated by Django 5.2 on 2025-07-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
